Insert into bookmarks (title, url, created_at) VALUES ('Kalyan Labs', 'https://lka.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs1', 'https://lka1.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs2', 'https://lka2.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs3', 'https://lka3.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs4', 'https://lka.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs5', 'https://lka1.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs6', 'https://lka2.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs7', 'https://lka3.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs8', 'https://lka.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs9', 'https://lka1.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs10', 'https://lka2.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs11', 'https://lka3.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs13', 'https://lka1.com', CURRENT_TIMESTAMP),
       ('Kalyan Labs14', 'https://lka2.com', CURRENT_TIMESTAMP)
;